org: brancusi
app: juice-core-dev
service: juicecore

custom:
  bucket: juice-core-pdfs

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: docs/generate-all
          method: post
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}
